# permissions for end users to view apolloportals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apolloportal-viewer-role
rules:
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloportals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloportals/status
  verbs:
  - get
