# permissions for end users to edit apolloes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apollo-editor-role
rules:
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloes/status
  verbs:
  - get
