# permissions for end users to view apolloenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apolloenvironment-viewer-role
rules:
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apolloconfig.com
  resources:
  - apolloenvironments/status
  verbs:
  - get
